// a10n - Wed Apr 20 14:10:58 2022
// String Matching (https://cses.fi/problemset/task/1753)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)
#define sz(x) (int)(x.size())

typedef vector<int> vi;
typedef pair<int, int> ii;

const int P = 31;
const int MOD = 1e9 + 7;
#define ctoi(c) (c - 'a' + 1)

inline int mod(int a) { return a %= MOD, a + (a < 0 ? MOD : 0); }
inline int powm(int a, int b) {
    if (!b) return 1;
    int c = powm(a, b / 2);
    c = mod(c * c);
    if (b & 1) c = mod(c * a);
    return c;
}
inline int invm(int a) { return powm(a, MOD - 2); }
inline int divm(int a, int b) { return mod(a * invm(b)); }

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);

    string s, p;
    cin >> s >> p;
    if (sz(p) > sz(s)) return 0;

    vi h(sz(s) + 1), pi(sz(s) + 1);

    pi[0] = 1;
    for (int i = 1; i <= sz(s); i++) pi[i] = mod(pi[i - 1] * P);

    h[0] = 0;
    for (int i = 1; i <= sz(s); i++)
        h[i] = mod((pi[i - 1] * ctoi(s[i - 1]) + h[i - 1]));

    int phash = 0;
    for (int i = 0; i < sz(p); i++) phash = mod(phash + pi[i] * ctoi(p[i]));

    int c = 0;
    for (int i = sz(p); i <= sz(s); i++) {
        int hh = mod(h[i] - h[i - sz(p)]);
        hh = divm(hh, pi[i - sz(p)]);
        if (hh == phash) c++;
    }

    cout << c << endl;
}
