# a10n - Wed Feb  9 00:44:18 2022
# Missing Number (https://cses.fi/problemset/task/1083)
# Generated by cptk

n = int(input())
a = sorted(int(x) for x in input().split(' '))
for i, j in zip(a, range(1, n)):
    if (i != j):
        print(j)
        break
else:
    print(n)
