// a10n - Wed Feb  9 22:50:32 2022
// Apple Division (https://cses.fi/problemset/task/1623)
// Generated by cptk

#include <iostream>
using namespace std;

#define int long long
int n, a[20];

int solve(int i, int ac, int bc) {
    if (i == n) return abs(ac - bc);
    return min(solve(i + 1, ac + a[i], bc), solve(i + 1, ac, bc + a[i]));
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cin >> n;
    for (int i = 0; i < n; i++) cin >> a[i];
    cout << solve(0, 0, 0) << endl;
}
