// a10n - Mon Apr 11 14:18:49 2022
// Polygon Area (https://cses.fi/problemset/task/2191)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)
#define x first
#define y second

typedef pair<int, int> ii;
typedef vector<ii> vii;

istream& operator>>(istream& in, ii& p) { return cin >> p.x >> p.y; }

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n;
    cin >> n;
    vii v(n);
    fori(n, i) cin >> v[i];
    v.push_back(v[0]);
    int s = 0;
    fori(n, i) s += (v[i].x - v[i + 1].x) * (v[i].y + v[i + 1].y);
    cout << abs(s) << endl;
}
