// a10n - Wed Apr 20 16:26:53 2022
// Finding Borders (https://cses.fi/problemset/task/1732)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)
#define sz(x) (int)(x.size())
#define ctoi(c) (c - 'a' + 1)

typedef vector<int> vi;
const int MOD = 1e9 - 63, P = 31;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);

    string s;
    cin >> s;
    int n = sz(s);

    vi h(n + 1);
    for (int i = 1, p = 1; i <= n; i++, p *= P, p %= MOD)
        h[i] = h[i - 1] + ctoi(s[i - 1]) * p, h[i] %= MOD;

    int hh = 0;
    for (int l = 1; l < n; l++) {
        int i = n - l;
        hh *= P, hh += ctoi(s[i]), hh %= MOD;
        if (h[l] == hh) cout << l << ' ';
    }
    cout << endl;
}
