// a10n - Sat Mar 12 11:17:05 2022
// Finding a Centroid (https://cses.fi/problemset/task/2079)
// Generated by cptk

// clang-format off
#include <bits/stdc++.h>
using namespace std;
void _main();
#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)
#define main signed main() { cin.tie(NULL)->sync_with_stdio(false); \
    cout<<fixed<<setprecision(10); _main(); } void _main()
typedef vector<int> vi;
typedef pair<int, int> ii;
// clang-format on

const int maxn = 2e5 + 1;
vi g[maxn];
int sizes[maxn];
int n;

int calcsizes(int u, int f = 0) {
    int sz = 1;
    for (int v : g[u])
        if (v != f) sz += calcsizes(v, u);
    return sizes[u] = sz;
}

int findcenter(int u, int f = 0) {
    for (int v : g[u])
        if (v != f && sizes[v] > n / 2) return findcenter(v, u);
    return u;
}

main {
    cin >> n;
    fori(n - 1, i) {
        int u, v;
        cin >> u >> v;
        g[u].push_back(v), g[v].push_back(u);
    }
    calcsizes(1);
    cout << findcenter(1) << endl;
}
