// a10n - Mon Jan 31 22:45:45 2022
// Concert Tickets (https://cses.fi/problemset/task/1091)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;

    multiset<int> h;
    fori(n, i) {
        int x;
        cin >> x;
        h.insert(x);
    }

    fori(m, i) {
        int t;
        cin >> t;
        auto it = h.upper_bound(t);
        if (h.size() > 0 && it != h.begin()) {
            cout << *(--it) << endl;
            h.erase(it);
        } else {
            cout << -1 << endl;
        }
    }
}
