// a10n - Mon Jan 31 23:28:01 2022
// Playlist (https://cses.fi/problemset/task/1141)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n;
    cin >> n;

    int j = 0, res = 0;
    map<int, int> m;
    fori(n, i) {
        int k;
        cin >> k;
        if (m.count(k)) {
            res = max(res, i - j);
            j = max(j, m[k] + 1);
        }
        m[k] = i;
    }

    cout << max(res, n - j) << endl;
}
