// a10n - Thu Feb 10 23:30:13 2022
// Trailing Zeros (https://cses.fi/problemset/task/1618)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;
#define int long long

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, z = 0;
    cin >> n;
    for (int p = 5; p <= n; p *= 5) z += n / p;
    cout << z << endl;
}
