// a10n - Tue Feb  1 01:21:10 2022
// Digit Queries (https://cses.fi/problemset/task/2431)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;
#define int long long

void solve();
signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cout << fixed << setprecision(10);
    int t = 1;
    cin >> t;
    while (t--) solve();
}

void solve() {
    int n;
    cin >> n;
    int len = 1, mi = 1, i = 1;
    while ((9 * mi * len + i) <= n) i += 9 * mi * len, len++, mi *= 10;
    mi += (n - i) / len;
    len -= (n - i) % len;
    while (len > 1) mi /= 10, len--;
    cout << (mi % 10) << endl;
}
