// a10n - Thu Feb  3 20:37:47 2022
// Factory Machines (https://cses.fi/problemset/task/1620)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)
typedef vector<int> vi;

vi k;
inline int count(int d) {
    int s = 0;
    for (int c : k) s += d / c;
    return (s >= 0 ? s : 1e18);
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, t;
    cin >> n >> t;

    k.resize(n);
    fori(n, i) cin >> k[i];

    int lo = 0, hi = 1e18;
    while (lo < hi) {
        int mi = (lo + hi) / 2;
        if (count(mi) < t) {
            lo = mi + 1;
        } else {
            hi = mi;
        }
    }

    cout << lo << endl;
}
