// a10n - Mon Feb 28 13:48:30 2022
// Course Schedule (https://cses.fi/problemset/task/1679)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)
const int maxn = 1e5;
vector<int> g[maxn];

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;
    vector<int> in(n, 0);

    fori(m, i) {
        int a, b;
        cin >> a >> b;
        a--, b--;
        g[a].push_back(b), in[b]++;
    }

    queue<int> q, ans;
    fori(n, i) if (!in[i]) q.push(i);
    while (!q.empty()) {
        int a = q.front();
        ans.push(a), q.pop();
        for (int b : g[a])
            if (--in[b] == 0) q.push(b);
    }

    fori(n, i) if (in[i]) return cout << "IMPOSSIBLE" << endl, 0;
    while (!ans.empty()) {
        cout << ans.front() + 1 << ' ';
        ans.pop();
    }
    cout << endl;
}
