// a10n - {{ now.ctime() }}
// {{ problem.name }} ({{ problem.url }})
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
typedef vector<vi> vvi;
typedef pair<int, int> ii;
typedef tuple<int, int, int> iii;

void solve();
signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cout << fixed << setprecision(10);
    int t = 1;
    // cin >> t;
    while (t--) solve();
}

void solve() {}
