// a10n - {{ now.ctime() }}
// {{ problem.name }} ({{ problem.url }})
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
typedef pair<int, int> ii;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cout << fixed << setprecision(10);
}
