// a10n - Thu Mar  3 20:38:37 2022
// Forest Queries (https://cses.fi/problemset/task/1652)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

// clang-format off
void solution();
#define int long long
#define solution() signed main() { cin.tie(NULL)->sync_with_stdio(false); \
    cout<<fixed<<setprecision(10); solution(); } void solution()
// clang-format on

const int maxn = 1005;
int b[maxn][maxn];

solution() {
    int n, q;
    cin >> n >> q;

    for (int i = 0; i <= n; i++) b[i][0] = b[0][i] = 0;

    for (int i = 1; i <= n; i++)
        for (int j = 1; j <= n; j++) {
            char a;
            cin >> a;
            b[i][j] = (a == '*') + b[i - 1][j] + b[i][j - 1] - b[i - 1][j - 1];
        }

    while (q--) {
        int y1, x1, y2, x2;
        cin >> y1 >> x1 >> y2 >> x2;
        if (x1 > x2) swap(x1, x2);
        if (y1 > y2) swap(y1, y2);
        cout << b[y2][x2] - b[y2][x1 - 1] - b[y1 - 1][x2] + b[y1 - 1][x1 - 1]
             << endl;
    }
}
