// a10n - Sun Mar 27 12:25:27 2022
// Coin Combinations II (https://cses.fi/problemset/task/1636)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
const int MOD = 1e9 + 7;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);

    int n, x;
    cin >> n >> x;
    vi c(n);
    fori(n, i) cin >> c[i];
    sort(all(c));

    vi dp(x + 1, 0);
    dp[0] = 1;

    fori(n, coin) {
        for (int i = c[coin]; i <= x; i++) {
            dp[i] += dp[i - c[coin]];
            dp[i] %= MOD;
        }
    }

    cout << dp[x] << endl;
}
