// a10n - Tue Feb  1 16:05:03 2022
// Way Too Long Words (https://codeforces.com/problemset/problem/71/A)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

void solve();
signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cout << fixed << setprecision(10);
    int t = 1;
    cin >> t;
    while (t--) solve();
}

void solve() {
    string s;
    cin >> s;
    if (s.size() <= 10)
        cout << s << endl;
    else
        cout << s[0] << s.size() - 2 << s[s.size() - 1] << endl;
}
