# a10n - Wed Feb  9 00:49:46 2022
# Repetitions (https://cses.fi/problemset/task/1069)
# Generated by cptk

a = input()
m, c = 0, 1
for i, j in zip(a, a[1:]):
    if i == j:
        c += 1
    else:
        m = max(m, c)
        c = 1
print(max(m, c))
