// a10n - Mon Apr 11 10:47:06 2022
// Point Location Test (https://cses.fi/problemset/task/2189)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
typedef pair<int, int> ii;

void solve() {
    int x1, y1, x2, y2, x3, y3;
    cin >> x1 >> y1 >> x2 >> y2 >> x3 >> y3;
    x2 -= x1, y2 -= y1, x3 -= x1, y3 -= y1;
    int cross = x2 * y3 - x3 * y2;
    if (cross > 0) cout << "LEFT" << endl;
    if (cross == 0) cout << "TOUCH" << endl;
    if (cross < 0) cout << "RIGHT" << endl;
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int t;
    cin >> t;
    while (t--) solve();
}
