// a10n - Fri Mar 11 21:32:46 2022
// Planets Cycles (https://cses.fi/problemset/task/1751)
// Generated by cptk

// clang-format off
#include <bits/stdc++.h>
using namespace std;
void _main();
#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)
#define main signed main() { cin.tie(NULL)->sync_with_stdio(false); \
    cout<<fixed<<setprecision(10); _main(); } void _main()
typedef vector<int> vi;
// clang-format on

const int maxn = 2e5 + 5;
int t[maxn], ans[maxn];

bool cycle(int u, int d = 1) {
    // returns true if in cycle, false otherwise
    ans[u] = -d;
    if (ans[t[u]] > 0) {
        ans[u] = ans[t[u]] + 1;
        return false;
    } else if (ans[t[u]] < 0) {
        ans[u] = ans[t[u]] = d + ans[t[u]] + 1;
        return u != t[u];
    } else {
        bool cyc = cycle(t[u], d + 1);
        if (ans[u] > 0) return false;
        ans[u] = ans[t[u]] + !cyc;
        return cyc;
    }
}

main {
    int n;
    cin >> n;
    fori(n, i) cin >> t[i], t[i]--;
    fori(n, i) ans[i] = 0;
    fori(n, i) if (!ans[i]) cycle(i);
    fori(n, i) cout << ans[i] << ' ';
    cout << endl;
}
