# a10n - Wed Feb  9 00:54:40 2022
# Increasing Array (https://cses.fi/problemset/task/1094)
# Generated by cptk

n = int(input())
a = list(int(x) for x in input().split())
c, p = 0, a[0]
for i in a:
    c += max(p - i, 0)
    p = max(p, i)
print(c)
