// a10n - Wed Feb  2 19:41:15 2022
// Tower of Hanoi (https://cses.fi/problemset/task/2165)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

queue<pair<int, int>> moves;

void solve(int n, int from, int to, int use) {
    if (n == 0) return;
    solve(n - 1, from, use, to);
    moves.push({from, to});
    solve(n - 1, use, to, from);
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n;
    cin >> n;
    solve(n, 1, 3, 2);
    cout << moves.size() << endl;
    while (!moves.empty()) {
        cout << moves.front().first << ' ' << moves.front().second << endl;
        moves.pop();
    }
}
