// a10n - Mon Feb  7 13:35:19 2022
// Josephus Problem I (https://cses.fi/problemset/task/2162)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);

    int n;
    cin >> n;

    set<int> s;
    for (int i = 1; i <= n; i++) s.insert(i);

    auto it = ++s.begin();
    while (s.size() > 1) {
        if (it == s.end()) it = s.begin();
        cout << *it << ' ';
        s.erase(it++);
        if (it++ == s.end()) it = ++s.begin();
    }

    cout << *s.begin() << endl;
}
