// a10n - Sun Mar 27 12:59:59 2022
// Array Description (https://cses.fi/problemset/task/1746)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
const int MOD = 1e9 + 7;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;

    vi dp(m, 0), prv;

    {
        int x;
        cin >> x;
        n--, x--;
        if (x == -1)
            dp.assign(m, 1);
        else
            dp[x] = 1;
    }

    while (n--) {
        prv = dp;
        int x;
        cin >> x;
        x--;

        if (x == -1) {
            for (int i = 1; i < m; i++) dp[i] += prv[i - 1];
            for (int i = 0; i < m - 1; i++) dp[i] += prv[i + 1];
            for (int& v : dp) v %= MOD;
        } else {
            dp.assign(m, 0);
            dp[x] = prv[x];
            if (x > 0) dp[x] += prv[x - 1];
            if (x < m - 1) dp[x] += prv[x + 1];
            dp[x] %= MOD;
        }
    }

    int s = 0;
    for (int a : dp) s += a, s %= MOD;
    cout << s << endl;
}
