// a10n - Mon Feb  7 13:54:45 2022
// Josephus Problem II (https://cses.fi/problemset/task/2163)
// Generated by cptk

#include <bits/stdc++.h>

#include <ext/pb_ds/assoc_container.hpp>
#include <ext/pb_ds/tree_policy.hpp>

using namespace std;
using namespace __gnu_pbds;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

typedef tree<int, null_type, less<int>, rb_tree_tag,
             tree_order_statistics_node_update>
    statset;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);

    int n, k;
    cin >> n >> k;

    statset s;
    for (int i = 1; i <= n; i++) s.insert(i);

    auto cur = s.begin();
    while (s.size()) {
        int i = (s.order_of_key(*cur) + k) % s.size();
        cur = s.find_by_order(i);
        cout << *cur << ' ';
        s.erase(cur++);
    }

    cout << endl;
}
