// a10n - Sun Mar 27 21:33:59 2022
// Two Sets II (https://cses.fi/problemset/task/1093)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
const int MOD = 1e9 + 7;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n;
    cin >> n;

    if ((n + 1) * n % 4 != 0) return cout << 0 << endl, 0;

    int t = ((n + 1) * n) / 4;
    vi dp(t + 1, 0), prv;
    dp[1] = 1;

    for (int i = 2; i <= n; i++) {
        prv = dp;
        for (int s = i; s <= t; s++) {
            dp[s] += prv[s - i];
            dp[s] %= MOD;
        }
    }

    cout << dp[t] << endl;
}
