// a10n - Mon Jan 31 19:38:54 2022
// Building Roads (https://cses.fi/problemset/task/1666)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)
#define pb push_back
typedef vector<int> vi;

const int maxn = 1e5 + 5;
vi g[maxn];

void explore(int i, vector<bool>& mark) {
    if (mark[i]) return;
    mark[i] = true;
    for (int s : g[i]) explore(s, mark);
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;

    fori(m, i) {
        int a, b;
        cin >> a >> b;
        a--, b--;
        g[a].pb(b), g[b].pb(a);
    }

    vector<bool> mark(n, false);
    queue<int> roots;
    fori(n, i) if (!mark[i]) roots.push(i), explore(i, mark);

    cout << roots.size() - 1 << endl;
    while (roots.size() > 1) {
        int a = roots.front();
        roots.pop();
        int b = roots.front();
        cout << ++a << ' ' << ++b << endl;
    }
}
