// a10n - Thu Mar 24 21:22:47 2022
// Shortest Routes II (https://cses.fi/problemset/task/1672)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef pair<int, int> ii;
typedef vector<int> vi;
typedef vector<ii> vii;

const int maxn = 505;
vii g[maxn];
int d[maxn][maxn];

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);

    int n, m, q;
    cin >> n >> m >> q;
    fori(n, i) fori(n, j) d[i][j] = -1;
    fori(n, i) d[i][i] = 0;

    fori(m, i) {
        int a, b, c;
        cin >> a >> b >> c;
        a--, b--;
        g[a].push_back({b, c}), g[b].push_back({a, c});
        d[a][b] = d[b][a] = (d[a][b] == -1 ? c : min(c, d[a][b]));
    }

    fori(n, k) fori(n, i) fori(n, j) {
        if (d[i][k] != -1 && d[k][j] != -1) {
            if (d[i][j] == -1)
                d[i][j] = d[i][k] + d[k][j];
            else
                d[i][j] = min(d[i][k] + d[k][j], d[i][j]);
        }
    }

    while (q--) {
        int a, b;
        cin >> a >> b;
        a--, b--;
        cout << d[a][b] << endl;
    }
}
