// a10n - Tue Mar  1 10:56:59 2022
// Static Range Sum Queries (https://cses.fi/problemset/task/1646)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;
#define int long long

const int maxn = 2e5 + 5;
int a[maxn];

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, q;
    cin >> n >> q;
    a[0] = 0;
    for (int i = 1; i <= n; i++) {
        cin >> a[i];
        a[i] += a[i - 1];
    }

    while (q--) {
        int i, j;
        cin >> i >> j;
        cout << a[j] - a[i - 1] << endl;
    }
}
