// a10n - Sun Feb  6 10:51:36 2022
// Police Chase (https://cses.fi/problemset/task/1695)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
typedef vector<vi> vvi;
typedef vector<bool> vb;

struct flow {
    vvi g, c;
    int n, s, t, curf = 0;
    const int BIG = 1LL << 60;

    flow(int n, int s, int t)
        : g(n + 2), c(n + 2, vi(n + 2, 0)), n(n), s(s), t(t) {
        // We use node ss=n as the dummy source and tt=n+1 as the dummy sink.
        ss = n, tt = n + 1;
        g[ss].push_back(s), g[t].push_back(tt);
        c[ss][s] = BIG, c[t][tt] = BIG;
    };

    void add(int u, int v, int w) {
        c[u][v] += w;
        g[u].push_back(v), g[v].push_back(u);
    }

    int saturate() {
        // Adds flow to the flow network until it is saturated.
        // Uses the "Capacity Scaling" method: https://youtu.be/1ewLrXUz4kk
        // Returns the Max-Flow Min-Cut of the network when saturated.

        vb m(n, false);
        for (int r, f = BIG; f > 0; f /= 2, fill(all(m), false)) {
            while (r = improve(ss, s, f, BIG, m)) {
                fill(all(m), false);
                curf += r;
            }
        }

        return curf;
    }

   protected:
    int ss, tt;
    int improve(int u, int v, int minf, int maxf, vb& m) {
        // Preforms a single iteration of the capacity scaling algorithm.
        // Tries to add f units of flow to the network, starting from edge
        // (u,v), where minf<=f<=maxf. Returns the number of flow units added to
        // the total flow network. If can't add more flow to the networt, the
        // network is saturated, and 0 is returned.

        if (v == tt) return maxf;
        if (m[v] || c[u][v] < minf) return false;
        m[v] = true, maxf = min(maxf, c[u][v]);

        for (int k : g[v]) {
            int r = improve(v, k, minf, maxf, m);
            if (r) {
                c[u][v] -= r, c[v][u] += r;
                return r;
            }
        }

        return false;
    }
};

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;
    flow nf(n, 0, n - 1);

    fori(m, i) {
        int a, b;
        cin >> a >> b;
        a--, b--;
        nf.add(a, b, 1), nf.c[b][a]++;
    }

    cout << nf.saturate() << endl;

    vb v(n);
    stack<int> s;
    s.push(0);

    while (!s.empty()) {
        int c = s.top();
        s.pop();
        if (v[c]) continue;
        v[c] = true;
        for (int k : nf.g[c])
            if (nf.c[c][k] != 0) s.push(k);
    }

    fori(n, i) {
        if (!v[i]) continue;
        for (int j : nf.g[i]) {
            if (!v[j]) cout << i + 1 << ' ' << j + 1 << endl;
        }
    }
}
