// a10n - Mon Jan 31 22:16:58 2022
// Building Teams (https://cses.fi/problemset/task/1668)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)
#define pb push_back
typedef vector<int> vi;

const int maxn = 2e5 + 5;
vi g[maxn];

bool explore(bool a, int i, vi& groups) {
    if (groups[i] == -1) {
        groups[i] = a;
        bool res = true;
        for (int s : g[i]) res = res && explore(!a, s, groups);
        return res;
    }
    return groups[i] == a;
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;

    fori(m, i) {
        int a, b;
        cin >> a >> b;
        a--, b--;
        g[a].pb(b), g[b].pb(a);
    }

    vi groups(n, -1);
    bool res = true;
    fori(n, i) if (groups[i] == -1) res = res && explore(false, i, groups);

    if (res) {
        fori(n, i) cout << (groups[i] ? 1 : 2) << ' ';
        cout << endl;
    } else {
        cout << "IMPOSSIBLE" << endl;
    }
}
