// a10n - Sat Apr 16 01:15:00 2022
// List Removals (https://cses.fi/problemset/task/1749)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;
typedef pair<int, int> ii;

typedef struct seg {
    int lo, hi, mi, v = 1;
    seg *left = NULL, *right = NULL;

    seg(int lo, int hi) : lo(lo), hi(hi), mi((lo + hi) / 2) {
        if (lo < hi) {
            left = new seg(lo, mi), right = new seg(mi + 1, hi);
            pull();
        }
    }

    void pull() {
        v = 0;
        if (left) v += left->v;
        if (right) v += right->v;
    }

    int remove(int k) {
        if (lo == hi) {
            v = 0;
            return lo;
        } else {
            int r;
            if (k < left->v)
                r = left->remove(k);
            else
                r = right->remove(k - left->v);
            pull();
            return r;
        }
    }

} seg;

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n;
    cin >> n;

    seg seg(0, n - 1);
    vi x(n);
    fori(n, i) cin >> x[i];

    fori(n, _) {
        int k;
        cin >> k;
        int i = seg.remove(--k);
        cout << x[i] << endl;
    }
}
