// a10n - Fri Feb 18 22:40:40 2022
// Modulo Sum (https://codeforces.com/problemset/problem/577/B)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

bool solve() {
    int n, m;
    cin >> n >> m;
    vector<int> v(m, -1);

    fori(n, i) {
        int x;
        cin >> x;

        fori(m, j) {
            int mo = (j + x) % m;
            if (v[j] != -1 && v[j] != i && v[mo] == -1) {
                if (!mo) return true;
                v[mo] = i;
            }
        }

        v[x % m] = i;
        if (!(x % m)) return true;
    }

    return false;
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cout << (solve() ? "YES" : "NO") << endl;
}
