# a10n - Wed Feb  9 00:40:47 2022
# Weird Algorithm (https://cses.fi/problemset/task/1068)
# Generated by cptk

n = int(input())
while(n > 1):
    print(n, end=' ')
    n = (n * 3) + 1 if n % 2 else n // 2

print(n)
