// a10n - Sat Apr 16 11:31:52 2022
// Binomial Coefficients (https://cses.fi/problemset/task/1079)
// Generated by cptk

#include <iostream>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

const int maxn = 1e6 + 5;
const int MOD = 1e9 + 7;
int fac[maxn];

void precompute() {
    fac[0] = 1;
    for (int i = 1; i < maxn; i++) fac[i] = i * fac[i - 1], fac[i] %= MOD;
}

int powm(int a, int b) {
    if (b == 0) return 1;
    int c = powm(a, b / 2);
    c *= c, c %= MOD;
    if (b & 1) c *= a, c %= MOD;
    return c;
}

int invm(int a) { return powm(a, MOD - 2); }
int divm(int a, int b) { return (a * invm(b)) % MOD; }
int mulm(int a, int b) { return (a * b) % MOD; }
int choose(int n, int k) { return divm(fac[n], mulm(fac[k], fac[n - k])); }

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    precompute();
    int t;
    cin >> t;
    while (t--) {
        int n, k;
        cin >> n >> k;
        cout << choose(n, k) << endl;
    }
}
