// a10n - Tue Feb  1 00:19:47 2022
// Road Construction (https://cses.fi/problemset/task/1676)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

#define int long long
#define fori(n, i) for (int i = 0; i < n; i++)

typedef vector<int> vi;

int dsufind(vi& dsu, int a) {
    if (dsu[a] < 0) return a;
    return dsu[a] = dsufind(dsu, dsu[a]);
}

bool dsujoin(vi& dsu, int a, int b) {
    a = dsufind(dsu, a), b = dsufind(dsu, b);
    if (a == b) return false;
    int as = -dsu[a], bs = -dsu[b];
    if (as > bs) swap(a, b), swap(as, bs);
    dsu[a] = b, dsu[b] -= as;
    return true;
}

signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    int n, m;
    cin >> n >> m;
    vi dsu(n, -1);
    int ma = 1;
    fori(m, i) {
        int a, b;
        cin >> a >> b;
        a--, b--;
        n -= dsujoin(dsu, a, b);
        ma = max(ma, -dsu[dsufind(dsu, a)]);
        cout << n << ' ' << ma << endl;
    }
}
