// a10n - Sun Mar 13 13:50:48 2022
// Room Allocation (https://cses.fi/problemset/task/1164)
// Generated by cptk

// clang-format off
#include <bits/stdc++.h>
using namespace std;
void _main();
#define int long long
#define all(x) (x).begin(), (x).end()
#define fori(n, i) for (int i = 0; i < n; i++)
#define main signed main() { cin.tie(NULL)->sync_with_stdio(false); \
    cout<<fixed<<setprecision(10); _main(); } void _main()
typedef vector<int> vi;
typedef pair<int, int> ii;
// clang-format on

#define join(p) (p.second < 0)

main {
    int n;
    cin >> n;
    multiset<ii> s;
    for (int i = 1; i <= n; i++) {
        int a, b;
        cin >> a >> b;
        s.insert({a, -i}), s.insert({b, i});
    }

    int ma = 0, k = 0;
    for (auto p : s) k += (join(p) ? 1 : -1), ma = max(ma, k);

    vi ans(n + 1);
    set<int> avaliable;
    for (int i = 1; i <= ma; i++) avaliable.insert(i);

    for (auto p : s) {
        int i = abs(p.second);
        if (join(p)) {
            ans[i] = *avaliable.begin();
            avaliable.erase(avaliable.begin());
        } else {
            avaliable.insert(ans[i]);
        }
    }

    cout << ma << endl;
    for (int i = 1; i <= n; i++) cout << ans[i] << ' ';
    cout << endl;
}
