// a10n - Wed Mar  9 21:25:19 2022
// Planets Queries I (https://cses.fi/problemset/task/1750)
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

// clang-format off
void solve();
#define int long long
#define solve signed main() { cin.tie(NULL)->sync_with_stdio(false); \
    cout<<fixed<<setprecision(10); solve(); } void solve()
// clang-format on

const int maxn = 2e5 + 5, maxlogn = 30;
int s[maxn][maxlogn];

solve {
    int n, q;
    cin >> n >> q;
    for (int i = 1; i <= n; i++) cin >> s[i][0];
    for (int k = 1; k < maxlogn; k++)
        for (int i = 1; i <= n; i++) {
            s[i][k] = s[s[i][k - 1]][k - 1];
        }

    while (q--) {
        int x, k;
        cin >> x >> k;
        for (int i = maxlogn, di = pow(2, maxlogn); k; i--, di /= 2)
            if (k >= di) k -= di, x = s[x][i];
        cout << x << endl;
    }
}
